name: Unit Tests

on:
  pull_request:
    branches: [ main ] ## branches TBD
    types: [assigned, opened, synchronize, reopened, ready_for_review] ## Types TBD
  push:
    branches: [tcrone/gradle-clean-test-w-defaults]
  # Allows you to run this workflow manually from the Actions tab
  # Use context values as : ${{ github.event.inputs.BRANCH }}
  # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
  workflow_dispatch:
    inputs:
      BRANCH:
        description: "Specify branch (main is default)"
        required: false
        default: 'main'
# A workflow run is made up of one or more jobs. Jobs run in parallel by default.
jobs:
  test:
    name: Default Gradle Test
    timeout-minutes: 120
    runs-on: ubuntu-latest
    env:
      default-branch: "main"
      # we use this in env var for conditionals (secrets can't be used in conditionals)
      GRADLE_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8

      - name: Save JAVA_HOME as JDK8 for later usage
        run: |
          echo "Current JAVA_HOME = ${JAVA_HOME}"
          echo "ORG_GRADLE_PROJECT_jdk8=$JAVA_HOME" >> $GITHUB_ENV

      - name: Set gradle.properties
        run: |
          sed -i -e "s|jdk8=8|jdk8=${ORG_GRADLE_PROJECT_jdk8}|" gradle.properties.gha
          cat gradle.properties.gha
          rm gradle.properties
          mv gradle.properties.gha gradle.properties

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run tests
        if: ${{ env.GRADLE_KEY != '' }}
        env:
          CI: GHA
          JAVA_HOME: ${{ env.ORG_GRADLE_PROJECT_jdk8 }}
          GRADLE_ENTERPRISE_ACCESS_KEY: 34.229.76.228=${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
          GRADLE_CACHE_USER: gha
          GRADLE_CACHE_PASSWORD: ${{ secrets.GRADLE_CACHE_PASSWORD }}
          JRE: jre8
          LANGUAGE: polyglot
          TEST_TYPE: unit
        run: |
          ./gradlew --console=plain clean test

      - name: Run tests without cache and build scans
        if: ${{ env.GRADLE_KEY == '' }}
        env:
          JAVA_HOME: ${{ env.ORG_GRADLE_PROJECT_jdk8 }}
        run: |
          echo "*** NOT PUBLISHING BUILD SCANS ***"
          ./gradlew --console=plain clean test

      - name: Capture build reports
        # If previous step fails, run this step regardless
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-w-defaults
          # The regex for the path below will capture unit test HTML reports generated by gradle for all
          # related modules: (agent-bridge, newrelic-java, newrelic-api, etc).
          # However, it's critical that the previous build step does a ./gradlew clean or the regex will capture test reports
          # that were leftover in unrelated modules for functional and instrumentation tests.
          path: |
            **/build/reports/tests/*
